# -*- coding: utf-8 -*-
"""grafica aleatorio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXqeKCICZbK_5MMKrPEN7qNv2rZcoqiP
"""

import matplotlib.pylab as plt
import numpy as np

datos = np.genfromtxt("datos.dat")
t = np.linspace(0,100, len(datos))
plt.figure()
plt.scatter(t, datos, c ="red")
plt.grid()
plt.savefig("Grafica numeros aleatorios")
plt.show()

